bug fix and refactoring

diff --git a/tomat b/tomat
--- a/tomat
+++ b/tomat
@@ -8,15 +8,17 @@
 # https://www.gnu.org/licenses/gpl-3.0-standalone.html
 # Version: 0.1.2.1
 
+set -e
+
 echo "How many pomodoro sessions do you want to do? (input 1-10)"
 read sessions
 
 if [[ $sessions != ?(-)+([0-9]) ]] ; then
-  echo "$1 is an invalid input type."
+  echo "'$sessions' is an invalid input type."
   exit 3
 fi
 
-if [ $sessions -gt 10 ] 2>/dev/null || [ $sessions -eq 0 ] 2>/dev/null ; then
+if [[ $sessions -gt 10 || $sessions -le 0 ]] ; then
   echo "Your input is out of range."
   exit 4
 fi
